### ISSUE TITLE
Auto Patching - patches installing out of order

### ISSUE THREAD

**Issue by think0r** [vatesfr/xo-server#165]
I patched a couple of XenServer 6.5 SP1 servers.  I noticed a number of patches being installed out of order.

**Comment by olivierlambert** [comment]
Hi,

They are installed in the dependency order, meaning sometimes a patch needs a "parent" patch installed before.

On the other hand, a patch doesn't need to be installed because it's already inside a service pack (called "conflicts" patches in XenServer).

Thus, you can't have conflicts and "numerical" order doesn't matter here.

**Comment by think0r** [comment]
While I understand a later released patch may depend on a previous patch or that a later patch could replace a previous patch, but with service releases dependency could only work chronologically, so I can’t really make sense of why XS65ESP1010 and XS65ESP1005 would be the last two patches installed.

**Comment by julien-f** [comment]
I am not sure I understand your concern, is there a bug, do you think the automatic installation could be improved or you are just wondering how it works?

The current algorithm is to install all patches from the most recent to the oldest to avoid installing patches which are already contained in a newer one. Requirements are installed automatically when needed.

**Comment by think0r** [comment]
I guess my concern was that the patches we not being applied in the order in which they were released which I am pretty sure is what Citrix recommends.  I was also concerned when a few servers initially failed to install aforementioned updates, although rebooting remediated.  I couldn’t make sense of why those two were the last remaining unapplied updates.

**Comment by olivierlambert** [comment]
I think there is two things here:

* patch are installed by release date on our side. But as you can read, release date or sometimes not the patch number order. See http://updates.xensource.com/XenServer/updates.xml
* we got a XAPI issue after installing some patches, despite it worked well. It explains why you need to click again on the button to apply them all. Sadly, that's a XAPI problem: it doesn't respect the XML-RPC/JSON-RPC standard (malformed JSON). Probably fixed in XenServer Dundee.

So the patching process won't cause any trouble. The experience is just a little weird due to some XAPI issue and Citrix release date.
